<?php 
	header("Access-Control-Allow-Origin: *");
	header("Content-Type: application/json; charset=UTF-8");
	// ---------------------------------------------------------------------------
	$newUsuario=json_decode(file_get_contents('php://input'));  //get user from json generated by login function in loginService.js
	// if($user->mail=='kevinah95@gmail.com' && $user->pass=='1234') {
	// 	session_start();
	// 	$_SESSION['uid']=uniqid('ang_');
	// 	print($_SESSION['uid']);	
	// }
	
	$conn = oci_connect('PetSaviors', 'PetSaviors', 'localhost/DBPrueba');
	if (!$conn) {
	    $e = oci_error();
	    trigger_error(htmlentities($e['message'], ENT_QUOTES), E_USER_ERROR);
	}

	// Script SQL
	$sql = 'INSERT INTO USUARIOS (CORREOUSUARIO, NOMBRE, P_APELLIDO, S_APELLIDO, TELEFONO, CALIFICACION,NOTAS)'.
	       'VALUES( :correo, :nombre, :p_apellido, :s_apellido, :telefono, :calificacion,:notas)';

	// Prepara una sentencia de Oracle para su ejecución
	$stid = oci_parse($conn, $sql); // gestor de sentencia

	// Ligando campos con variables
	oci_bind_by_name($stid, ':correo', $newUsuario->correo);
	oci_bind_by_name($stid, ':nombre', $newUsuario->nombre);
	oci_bind_by_name($stid, ':p_apellido', $newUsuario->p_apellido);
	oci_bind_by_name($stid, ':s_apellido', $newUsuario->s_apellido);
	oci_bind_by_name($stid, ':telefono', $newUsuario->telefono);
	$quitar=5;
	oci_bind_by_name($stid, ':calificacion', $quitar);
	oci_bind_by_name($stid, ':notas', $newUsuario->notas);

	// ejecutando la sentencia
	$r = oci_execute($stid);
	// verifica el error
	if (!$r) {
	    $e = oci_error($stid);  // Para errores de oci_execute, pase el gestor de sentencia
	    print htmlentities($e['message']);
	    print "\n<pre>\n";
	    print htmlentities($e['sqltext']);
	    printf("\n%".($e['offset']+1)."s", "^");
	    print  "\n</pre>\n";
	}else{
		print('Genial');
	}

	// cierra la conexion
	oci_free_statement($stid);
	oci_close($conn);


	

?>