<?php
	
	$objeto=json_decode(file_get_contents('php://input'));  //get user from json generated by login function in loginService.js
	$conn = oci_connect('PetSaviors', 'PetSaviors', 'localhost/DBPrueba' );
	if (!$conn) {
	$e = oci_error();
	trigger_error(htmlentities($e['message'], ENT_QUOTES), E_USER_ERROR);
	}

	$stid2 = oci_parse($conn, "begin :respuesta := FORMULARIO_PAQ.AGREGAR_FORMULARIO2(
		:pTipo, :pRemitente, :pDestinatario, :pMensaje); end;");	
	$tipo = 'Formulario Test para Adoptar';
	oci_bind_by_name($stid2, ':pTipo', $tipo);
	oci_bind_by_name($stid2, ':pRemitente', $objeto[0]->SOLICITANTE);
	oci_bind_by_name($stid2, ':pDestinatario', $objeto[0]->DUENIO);
	$mensaje = 'Solicitud de Adopción';
	oci_bind_by_name($stid2, ':pMensaje', $mensaje);
	oci_bind_by_name($stid2, ':respuesta', $r, 256);
	echo $r;
	oci_execute($stid2);
	oci_free_statement($stid2);

	for ($i=0; $i < count($objeto); $i++) {
		$stid = oci_parse($conn, "begin RESPUESTAS_USER_PKG.registrar_respuesta(
		:id_p, :id_form, :c_pregunta, :c_responde, :id_pet, :c_resp); end;");
		$idPregunta = (int)$objeto[$i]->ID_PREGUNTAS;
		oci_bind_by_name($stid, ':id_p', $idPregunta);
		oci_bind_by_name($stid, ':id_form', $r);
		oci_bind_by_name($stid, ':c_pregunta', $objeto[$i]->SOLICITANTE);
		oci_bind_by_name($stid, ':c_responde', $objeto[$i]->DUENIO);
		$idMascota = (int)$objeto[$i]->IDMASCOTA;
		oci_bind_by_name($stid, ':id_pet', $idMascota);
		oci_bind_by_name($stid, ':c_resp', $objeto[$i]->RESPUESTA);

		oci_execute($stid);
	}
	
	
	
	echo 'Enviada';
	
	
		
?>