<?php 
	
	$user=json_decode(file_get_contents('php://input'));  //get user from json generated by login function in loginService.js

	$conn = oci_connect('PetSaviors', 'PetSaviors', 'localhost/DBPrueba');
	if (!$conn) {
	    $e = oci_error();
	    trigger_error(htmlentities($e['message'], ENT_QUOTES), E_USER_ERROR);
	}

	$stid = oci_parse($conn, "begin :retorna := USUARIOS_PAQ.VERIFICAR_USUARIO( '".$user->mail."','".$user->pass."'); end;");
	oci_bind_by_name($stid, ':retorna', $respuesta, 20);
	// if (!$stid) {
	// }else{
	// };

	oci_execute($stid);
	if(!empty($respuesta)){
		
		session_start();
		$_SESSION['uid']=uniqid('ang_');
		print($_SESSION['uid']);	
	};
		
	
	

	
		
?>