--Disparadores que completan los campos de auditoría para cada tabla existente en el momento de insertar o actualizar datos.

--------Before insert
CREATE OR REPLACE TRIGGER BI_CALIFICACIONES BEFORE INSERT ON ALL_CALIFICACIONES FOR EACH ROW                                                                                                                                                                                                                                        
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_CALIFICACIONES; 
/
CREATE OR REPLACE TRIGGER BI_ADOPCIONES BEFORE INSERT ON ADOPCIONES FOR EACH ROW                                                                                                                                                                                                                                        
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_ADOPCIONES; 
/
CREATE OR REPLACE TRIGGER BI_FOTOS_ADOPCIONES BEFORE INSERT ON FOTOS_ADOPCIONES FOR EACH ROW                                                                                                                                                                                                                                        
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_FOTOS_ADOPCIONES;                                                                                                                                                                                                                                                                                                     
/
CREATE OR REPLACE TRIGGER BI_ANIMAL_TIENE_RAZA BEFORE INSERT ON ANIMAL_TIENE_RAZA FOR EACH ROW                                                                                                                                                                                                                          
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_ANIMAL_TIENE_RAZA;                                                                                                                                                                                                                                                                                               
/
CREATE OR REPLACE TRIGGER BI_ESTADO_DE_SALUD BEFORE INSERT ON ESTADO_DE_SALUD FOR EACH ROW                                                                                                                                                                                                                              
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_ESTADO_DE_SALUD;                                                                                                                                                                                                                                                                                                 
/
CREATE OR REPLACE TRIGGER BI_FORMULARIO BEFORE INSERT ON FORMULARIO FOR EACH ROW                                                                                                                                                                                                                                        
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_FORMULARIO;                                                                                                                                                                                                                                                                                                      
/
CREATE OR REPLACE TRIGGER BI_FORM_TIENE_PREGUNTAS BEFORE INSERT ON FORM_TIENE_PREGUNTAS FOR EACH ROW                                                                                                                                                                                                                    
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_FORM_TIENE_PREGUNTAS;                                                                                                                                                                                                                                                                                            
/
CREATE OR REPLACE TRIGGER BI_MASCOTAS BEFORE INSERT ON MASCOTAS FOR EACH ROW                                                                                                                                                                                                                                            
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_MASCOTAS;                                                                                                                                                                                                                                                                                                        
/
CREATE OR REPLACE TRIGGER BI_NOTIFICACIONES BEFORE INSERT ON NOTIFICACIONES FOR EACH ROW                                                                                                                                                                                                                                
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_NOTIFICACIONES;                                                                                                                                                                                                                                                                                                  
/
CREATE OR REPLACE TRIGGER BI_PREGUNTAS BEFORE INSERT ON PREGUNTAS FOR EACH ROW                                                                                                                                                                                                                                          
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_PREGUNTAS;                                                                                                                                                                                                                                                                                                       
/
CREATE OR REPLACE TRIGGER BI_RAZA BEFORE INSERT ON RAZA FOR EACH ROW                                                                                                                                                                                                                                                    
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_RAZA;                                                                                                                                                                                                                                                                                                            
/
CREATE OR REPLACE TRIGGER BI_RESPUESTAS BEFORE INSERT ON RESPUESTAS FOR EACH ROW                                                                                                                                                                                                                                        
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_RESPUESTAS;                                                                                                                                                                                                                                                                                                      
/

CREATE OR REPLACE TRIGGER BI_RESPUESTAS_USER BEFORE INSERT ON RESPUESTAS_USER FOR EACH ROW                                                                                                                                                                                                                                        
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_RESPUESTAS_USER;                                                                                                                                                                                                                                                                                                      
/

CREATE OR REPLACE TRIGGER BI_TIPO_DE_ANIMAL BEFORE INSERT ON TIPO_DE_ANIMAL FOR EACH ROW                                                                                                                                                                                                                                
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_TIPO_DE_ANIMAL;                                                                                                                                                                                                                                                                                                  
/
CREATE OR REPLACE TRIGGER BI_USUARIOS BEFORE INSERT ON USUARIOS FOR EACH ROW                                                                                                                                                                                                                                            
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_USUARIOS;                                                                                                                                                                                                                                                                                                        
/
CREATE OR REPLACE TRIGGER BI_DEVOLUCIONES BEFORE INSERT ON DEVOLUCIONES FOR EACH ROW                                                                                                                                                                                                                                            
BEGIN                                                                                                                                                                                                                                                                                                                   
  :NEW.USUARIO_CREACION:=USER;                                                                                                                                                                                                                                                                                          
  :NEW.FECHA_CREACION:=SYSDATE;                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                        
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                                                                                               
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                                                                                    
END BI_DEVOLUCIONES;                                                                                                                                                                                                                                                                                                        
/
---Before update
CREATE OR REPLACE TRIGGER BU_ADOPCIONES BEFORE UPDATE ON ADOPCIONES FOR EACH ROW                                                                                                                                                                      
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_ADOPCIONES;    
/
CREATE OR REPLACE TRIGGER BU_FOTOS_ADOPCIONES BEFORE UPDATE ON FOTOS_ADOPCIONES FOR EACH ROW                                                                                                                                                                      
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_FOTOS_ADOPCIONES;                                                                                                                                                                                                                                 
/
CREATE OR REPLACE TRIGGER BU_ANIMAL_TIENE_RAZA BEFORE UPDATE ON ANIMAL_TIENE_RAZA FOR EACH ROW                                                                                                                                                        
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_ANIMAL_TIENE_RAZA;                                                                                                                                                                                                                             
/
CREATE OR REPLACE TRIGGER BU_ESTADO_DE_SALUD BEFORE UPDATE ON ESTADO_DE_SALUD FOR EACH ROW                                                                                                                                                            
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_ESTADO_DE_SALUD;                                                                                                                                                                                                                               
/
CREATE OR REPLACE TRIGGER BU_FORMULARIO BEFORE UPDATE ON FORMULARIO FOR EACH ROW                                                                                                                                                                      
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_FORMULARIO;                                                                                                                                                                                                                                    
/
CREATE OR REPLACE TRIGGER BU_FORM_TIENE_PREGUNTAS BEFORE UPDATE ON FORM_TIENE_PREGUNTAS FOR EACH ROW                                                                                                                                                  
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_FORM_TIENE_PREGUNTAS;                                                                                                                                                                                                                          
/
CREATE OR REPLACE TRIGGER BU_MASCOTAS BEFORE UPDATE ON MASCOTAS FOR EACH ROW                                                                                                                                                                          
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_MASCOTAS;                                                                                                                                                                                                                                      
/
CREATE OR REPLACE TRIGGER BU_NOTIFICACIONES BEFORE UPDATE ON NOTIFICACIONES FOR EACH ROW                                                                                                                                                              
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_NOTIFICACIONES;                                                                                                                                                                                                                                
/
CREATE OR REPLACE TRIGGER BU_PREGUNTAS BEFORE UPDATE ON PREGUNTAS FOR EACH ROW                                                                                                                                                                        
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_PREGUNTAS;                                                                                                                                                                                                                                     
/
CREATE OR REPLACE TRIGGER BU_RAZA BEFORE UPDATE ON RAZA FOR EACH ROW                                                                                                                                                                                  
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_RAZA;                                                                                                                                                                                                                                          
/
CREATE OR REPLACE TRIGGER BU_RESPUESTAS BEFORE UPDATE ON RESPUESTAS FOR EACH ROW                                                                                                                                                                      
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_RESPUESTAS;                                                                                                                                                                                                                                    
/
CREATE OR REPLACE TRIGGER BU_RESPUESTAS_USER BEFORE UPDATE ON RESPUESTAS_USER FOR EACH ROW                                                                                                                                                                      
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_RESPUESTAS_USER;                                                                                                                                                                                                                                    
/
CREATE OR REPLACE TRIGGER BU_DEVOLUCIONES BEFORE UPDATE ON DEVOLUCIONES FOR EACH ROW                                                                                                                                                                      
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_DEVOLUCIONES;                                                                                                                                                                                                                                    
/
CREATE OR REPLACE TRIGGER BU_TIPO_DE_ANIMAL BEFORE UPDATE ON TIPO_DE_ANIMAL FOR EACH ROW                                                                                                                                                              
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_TIPO_DE_ANIMAL;                                                                                                                                                                                                                                
/
CREATE OR REPLACE TRIGGER BU_USUARIOS BEFORE UPDATE ON USUARIOS FOR EACH ROW                                                                                                                                                                          
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_USUARIOS;                                                                                                                                                                                                                                      
/
CREATE OR REPLACE TRIGGER BU_CALIFICACIONES BEFORE UPDATE ON ALL_CALIFICACIONES FOR EACH ROW                                                                                                                                                                          
BEGIN                                                                                                                                                                                                                                                 
  :NEW.USUARIO_ULTIMA_MODIFICACION:=USER;                                                                                                                                                                                                             
  :NEW.ULTIMA_MODIFICACION:=SYSDATE;                                                                                                                                                                                                                  
END BU_CALIFICACIONES; 
/