create or replace PACKAGE FORMULARIO_PAQ AS 
--Función que agrega un formulario a la tabla formularios y genera una notificación para el adoptante.
   FUNCTION AGREGAR_FORMULARIO( 
    pTIPO FORMULARIO.TIPO_FORMULARIO%TYPE, 
    pREMITENTE NOTIFICACIONES.REMITENTE%TYPE, 
    pDESTINATARIO NOTIFICACIONES.DESTINATARIO%TYPE, 
    pMENSAJE NOTIFICACIONES.MENSAJE%TYPE)
   RETURN VARCHAR2;
   FUNCTION AGREGAR_FORMULARIO2( 
    pTIPO FORMULARIO.TIPO_FORMULARIO%TYPE, 
    pREMITENTE NOTIFICACIONES.REMITENTE%TYPE, 
    pDESTINATARIO NOTIFICACIONES.DESTINATARIO%TYPE, 
    pMENSAJE NOTIFICACIONES.MENSAJE%TYPE,
    pMASCOTA NOTIFICACIONES.ID_MASCOTA%TYPE)
   RETURN NUMBER;
--Procedimiento que mediante un cursor obtiene las preguntas de un formulario
   PROCEDURE get_Preguntas(pCursor OUT SYS_REFCURSOR);
   --Procedimiento que mediante un cursor obtiene los items de un formulario
   PROCEDURE get_Items(pCursor OUT SYS_REFCURSOR); 
  --Procedimiento que mediante un cursor obtiene las preguntas de un formulario
   PROCEDURE get_Preguntas_Adopcion(pCursor OUT SYS_REFCURSOR);
   --Procedimiento que mediante un cursor obtiene los items de un formulario
   PROCEDURE get_Items_Adopcion(pCursor OUT SYS_REFCURSOR, pID_FORM FORMULARIO.TIPO_FORMULARIO%TYPE);
END FORMULARIO_PAQ;
------------------------------------------
/
create or replace PACKAGE BODY FORMULARIO_PAQ AS 

FUNCTION AGREGAR_FORMULARIO( 
    pTIPO FORMULARIO.TIPO_FORMULARIO%TYPE, 
    pREMITENTE NOTIFICACIONES.REMITENTE%TYPE, 
    pDESTINATARIO NOTIFICACIONES.DESTINATARIO%TYPE, 
    pMENSAJE NOTIFICACIONES.MENSAJE%TYPE)
   RETURN VARCHAR2
IS
   BEGIN 
        INSERT ALL
        INTO FORMULARIO("ID_FORMULARIO","TIPO_FORMULARIO")
        VALUES(S_IDFORMULARIO.NEXTVAL,pTIPO)
        INTO NOTIFICACIONES ("ID_NOTIFICACION","ID_FORMULARIO","REMITENTE","DESTINATARIO","MENSAJE")
        VALUES(S_IDFORMULARIO.CURRVAL,S_IDFORMULARIO.CURRVAL,pREMITENTE,pDESTINATARIO,pMENSAJE)
        SELECT * FROM dual;
        COMMIT;   
        RETURN 'Insertado';
   EXCEPTION
     WHEN DUP_VAL_ON_INDEX
     THEN
     RETURN 'Error';   
      
   END; 
   
FUNCTION AGREGAR_FORMULARIO2( 
    pTIPO FORMULARIO.TIPO_FORMULARIO%TYPE, 
    pREMITENTE NOTIFICACIONES.REMITENTE%TYPE, 
    pDESTINATARIO NOTIFICACIONES.DESTINATARIO%TYPE, 
    pMENSAJE NOTIFICACIONES.MENSAJE%TYPE,
    pMASCOTA NOTIFICACIONES.ID_MASCOTA%TYPE)
   RETURN NUMBER
AS
  retval   NUMBER; 
   BEGIN 
        SELECT S_IDFORMULARIO.NEXTVAL 
     INTO retval 
     FROM DUAL; 
        INSERT ALL
        INTO FORMULARIO("ID_FORMULARIO","TIPO_FORMULARIO")
        VALUES(retval,pTIPO)
        INTO NOTIFICACIONES ("ID_NOTIFICACION","ID_FORMULARIO","REMITENTE","DESTINATARIO","MENSAJE","ID_MASCOTA")
        VALUES(S_IDFORMULARIO.CURRVAL,S_IDFORMULARIO.CURRVAL,pREMITENTE,pDESTINATARIO,pMENSAJE,pMASCOTA)
        SELECT * FROM dual;
        COMMIT;   
        RETURN retval;
   EXCEPTION
     WHEN DUP_VAL_ON_INDEX
     THEN
     RETURN 'Error';   
      
   END; 

PROCEDURE get_Preguntas(pCursor OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN pCursor 
    FOR select * 
    FROM PREGUNTAS p
  JOIN FORM_TIENE_PREGUNTAS ftp
    ON ftp.ID_PREGUNTAS = p.ID_PREGUNTAS
  JOIN FORMULARIO f
    ON f.ID_FORMULARIO = ftp.ID_FORMUARIO
 WHERE f.ID_FORMULARIO = 1;
END get_Preguntas;
  
PROCEDURE get_Items(pCursor OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN pCursor 
    FOR select * from RESPUESTAS Where ID_FORMULARIO = 1;
  END get_Items;

PROCEDURE get_Preguntas_Adopcion(pCursor OUT SYS_REFCURSOR) AS
  BEGIN
    OPEN pCursor 
    FOR select * 
    FROM PREGUNTAS p
  JOIN FORM_TIENE_PREGUNTAS ftp
    ON ftp.ID_PREGUNTAS = p.ID_PREGUNTAS
  JOIN FORMULARIO f
    ON f.ID_FORMULARIO = ftp.ID_FORMUARIO
 WHERE f.ID_FORMULARIO = 2;
END get_Preguntas_Adopcion;

PROCEDURE get_Items_Adopcion(pCursor OUT SYS_REFCURSOR, pID_FORM FORMULARIO.TIPO_FORMULARIO%TYPE) AS
  BEGIN
    OPEN pCursor 
    FOR select * from RESPUESTAS_USER Where ID_FORMULARIO = pID_FORM ORDER BY ID_PREGUNTA;
  END get_Items_Adopcion;


END FORMULARIO_PAQ;


--declare
  -- result VARCHAR2(256);
--BEGIN
   ----------------CORREO,NOMBRE,P_APELLIDO,S_APELLIDO,CONTRASENIA,TElEFONO,ES_RESCATISTA,ESADOPTANTE
    --result := FORMULARIO_PAQ.AGREGAR_FORMULARIO('ADOPCION','jo1998aq@hotmail.com','jm95aguilar@hotmail.com','Me Gusta La Mascota Que Tiene en Adopcion');
  -- DBMS_OUTPUT.put_line(result);
--END;