--Inserciones de preguntas relacionadas al formulario para aprobación de adopciones
INSERT INTO "PETSAVIORS"."FORMULARIO" (ID_FORMULARIO, TIPO_FORMULARIO) VALUES ('2', 'Formulario Test para Adoptar');

-- Preguntas
INSERT INTO "PETSAVIORS"."PREGUNTAS" (ID_PREGUNTAS, CONTENIDO_PREGUNTA) VALUES ('8', '¿Posee patio y de ser así, cuál es su tamaño?');
INSERT INTO "PETSAVIORS"."PREGUNTAS" (ID_PREGUNTAS, CONTENIDO_PREGUNTA) VALUES ('9', '¿Cuánto tiempo le puede dedicar a su mascota?');
INSERT INTO "PETSAVIORS"."PREGUNTAS" (ID_PREGUNTAS, CONTENIDO_PREGUNTA) VALUES ('10', '¿Posee una casa propia o es rentada?');
INSERT INTO "PETSAVIORS"."PREGUNTAS" (ID_PREGUNTAS, CONTENIDO_PREGUNTA) VALUES ('11', '¿Posee otras mascotas? ¿Cuántas posee actualmente?');
INSERT INTO "PETSAVIORS"."PREGUNTAS" (ID_PREGUNTAS, CONTENIDO_PREGUNTA) VALUES ('12', 'Si ha tenido mascotas anteriormente ¿Cuál es el contacto de su veterinario?');
INSERT INTO "PETSAVIORS"."PREGUNTAS" (ID_PREGUNTAS, CONTENIDO_PREGUNTA) VALUES ('13', '¿La mascota debe interactuar con niños en su hogar?');

-- Relacion
INSERT INTO "PETSAVIORS"."FORM_TIENE_PREGUNTAS" (ID_FORMUARIO, ID_PREGUNTAS) VALUES ('2', '8');
INSERT INTO "PETSAVIORS"."FORM_TIENE_PREGUNTAS" (ID_FORMUARIO, ID_PREGUNTAS) VALUES ('2', '9');
INSERT INTO "PETSAVIORS"."FORM_TIENE_PREGUNTAS" (ID_FORMUARIO, ID_PREGUNTAS) VALUES ('2', '10');
INSERT INTO "PETSAVIORS"."FORM_TIENE_PREGUNTAS" (ID_FORMUARIO, ID_PREGUNTAS) VALUES ('2', '11');
INSERT INTO "PETSAVIORS"."FORM_TIENE_PREGUNTAS" (ID_FORMUARIO, ID_PREGUNTAS) VALUES ('2', '12');
INSERT INTO "PETSAVIORS"."FORM_TIENE_PREGUNTAS" (ID_FORMUARIO, ID_PREGUNTAS) VALUES ('2', '13');

-- ///Falta ver como asociar respuestas
